[package]
name = "kernel"
version = "0.1.0"
authors = ["Luuk van Oijen <lazyluuk.channel@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.10.0-alpha-02"
spin = "0.7.1"

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]
